/**
 * PushPlatform Client SDK  v1.2
 * Drop-in script for subscriber-facing websites.
 * Usage: embedded via the <script> snippet generated by the Admin Dashboard.
 */
(function () {
    'use strict';

    const config = window.PushPlatformConfig || {};
    const { siteId, apiUrl, sdkToken, promptMode = 'native', promptDelayMs = 3000 } = config;

    if (!siteId || !apiUrl || !sdkToken) {
        console.warn('[PushPlatform] Missing configuration. Ensure PushPlatformConfig is set before this script loads.');
        return;
    }

    // ─── Utility ────────────────────────────────────────────────────────────────
    function urlBase64ToUint8Array(base64String) {
        const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
        const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
        const raw = window.atob(base64);
        return new Uint8Array([...raw].map(c => c.charCodeAt(0)));
    }

    async function request(method, path, body, headers = {}) {
        const res = await fetch(apiUrl + path, {
            method,
            headers: { 'Content-Type': 'application/json', 'X-Site-Token': sdkToken, ...headers },
            body: body ? JSON.stringify(body) : undefined,
            credentials: 'omit',
        });
        return res;
    }

    // ─── Core API ────────────────────────────────────────────────────────────────
    async function getSiteConfig() {
        try {
            const res = await fetch(`${apiUrl}/api/site/${siteId}/config`);
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            return await res.json();
        } catch (e) {
            console.error('[PushPlatform] Could not load site config:', e.message);
            return null;
        }
    }

    async function registerSubscription(vapidPublicKey, useLocalSw) {
        if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
            console.warn('[PushPlatform] Push API not supported in this browser.');
            return null;
        }

        // Register SW. If useLocalSw is true, use the site's own sw.js
        const swUrl = useLocalSw ? '/sw.js' : `${apiUrl}/sdk/sw.js`;
        let reg;
        try {
            reg = await navigator.serviceWorker.register(swUrl, { scope: '/' });
            console.log('[PushPlatform] Service worker registered. Scope:', reg.scope);
        } catch (e) {
            console.error('[PushPlatform] Service worker registration failed:', e.message);
            return null;
        }


        await navigator.serviceWorker.ready;

        // Check if already subscribed
        let subscription = await reg.pushManager.getSubscription();
        if (!subscription) {
            try {
                subscription = await reg.pushManager.subscribe({
                    userVisibleOnly: true,
                    applicationServerKey: urlBase64ToUint8Array(vapidPublicKey),
                });
                console.log('[PushPlatform] Push subscription created.');
            } catch (e) {
                console.warn('[PushPlatform] Subscription failed (user may have denied):', e.message);
                return null;
            }
        } else {
            console.log('[PushPlatform] Reusing existing push subscription.');
        }

        // Send to backend
        const subJson = subscription.toJSON();
        const ua = navigator.userAgent;
        const browser = detectBrowser(ua);
        const os = detectOS(ua);

        try {
            const res = await request('POST', '/api/subscribe', {
                endpoint: subJson.endpoint,
                p256dh: subJson.keys.p256dh,
                auth: subJson.keys.auth,
                browser,
                os,
                site_id: siteId,
            });

            if (!res.ok) {
                const body = await res.json().catch(() => ({}));
                console.error(`[PushPlatform] Subscription API error ${res.status}:`, body.message || body);
                return null;
            }

            const data = await res.json();
            console.log('[PushPlatform] Subscriber registered successfully. ID:', data.subscriber_id);

            // Store locally for tag operations
            try { localStorage.setItem('pp_endpoint', subJson.endpoint); } catch { }
            return subscription;
        } catch (e) {
            console.error('[PushPlatform] Failed to POST subscription to server:', e.message);
            return null;
        }
    }

    // ─── Permission Prompt ───────────────────────────────────────────────────────
    function openBridgePopup(vapidPublicKey) {
        const popupUrl = `${apiUrl}/sdk/bridge.html?mode=popup&siteId=${siteId}&sdkToken=${sdkToken}&vapidPublicKey=${encodeURIComponent(vapidPublicKey)}&origin=${encodeURIComponent(window.location.hostname)}`;
        const w = 450; const h = 500;
        const left = (screen.width - w) / 2;
        const top = (screen.height - h) / 2;
        window.open(popupUrl, 'PushPlatformPrompt', `scrollbars=yes,resizable=yes,status=no,location=no,toolbar=no,menubar=no,width=${w},height=${h},left=${left},top=${top}`);
    }

    function requestPermission(vapidPublicKey, bridgeRequired, useLocalSw) {
        if (bridgeRequired) {
            openBridgePopup(vapidPublicKey);
        } else {
            Notification.requestPermission().then(async (perm) => {
                if (perm === 'granted') {
                    await registerSubscription(vapidPublicKey, useLocalSw);
                    removeWidget();
                }
            });
        }
    }

    async function init() {
        const siteConfig = await getSiteConfig();
        if (!siteConfig) return;
        const vapidPublicKey = siteConfig.vapid_public_key;
        const mode = promptMode || siteConfig.prompt_mode || 'native';
        const delayMs = promptDelayMs || siteConfig.prompt_delay_ms || 3000;

        const isCrossOrigin = window.location.origin !== new URL(apiUrl).origin;

        // Check if the user's custom domain is hosting sw.js at the root
        let useLocalSw = false;
        if (isCrossOrigin) {
            try {
                const res = await fetch('/sw.js', { method: 'HEAD' });
                if (res.ok) useLocalSw = true;
            } catch (e) { } // Network error or not found
        }

        const bridgeRequired = isCrossOrigin && !useLocalSw;

        // Listen for messages from popup or iframe
        window.addEventListener('message', (event) => {
            if (!event.data) return;
            if (event.data.type === 'PUSH_PLATFORM_REGISTER_SUCCESS') {
                try { localStorage.setItem('pp_endpoint', event.data.endpoint); } catch { }
                removeWidget();
            } else if (event.data.type === 'PUSH_PLATFORM_BRIDGE_READY') {
                // If not already subscribed, show prompt
                if (mode === 'native') {
                    setTimeout(() => showBellWidget(vapidPublicKey, bridgeRequired, useLocalSw), delayMs);
                } else {
                    setTimeout(() => showBellWidget(vapidPublicKey, bridgeRequired, useLocalSw), delayMs);
                }
            } else if (event.data.type === 'PUSH_PLATFORM_REGISTER_ERROR') {
                console.error('[PushPlatform]', event.data.error);
            }
        });

        if (bridgeRequired) {
            // Check silently first
            const iframe = document.createElement('iframe');
            iframe.style.display = 'none';
            iframe.src = `${apiUrl}/sdk/bridge.html?mode=iframe&siteId=${siteId}&sdkToken=${sdkToken}&vapidPublicKey=${encodeURIComponent(vapidPublicKey)}`;
            document.body.appendChild(iframe);
            return;
        }

        if (!('Notification' in window)) {
            console.warn('[PushPlatform] Notifications are not supported by this browser or not running in a secure context (HTTPS).');
            return;
        }

        // If already granted — silently re-register (catch endpoint changes)
        if (Notification.permission === 'granted') {
            await registerSubscription(vapidPublicKey, useLocalSw);
            return;
        }

        if (Notification.permission === 'denied') return;

        if (mode === 'native') {
            setTimeout(() => requestPermission(vapidPublicKey, bridgeRequired, useLocalSw), delayMs);
        } else {
            setTimeout(() => showBellWidget(vapidPublicKey, bridgeRequired, useLocalSw), delayMs);
        }
    }

    // ─── Custom Bell Widget ──────────────────────────────────────────────────────
    function showBellWidget(vapidPublicKey, bridgeRequired, useLocalSw) {
        if (document.getElementById('pp-widget')) return;

        const style = document.createElement('style');
        style.textContent = `
      #pp-widget { position: fixed; bottom: 20px; right: 20px; z-index: 999999; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
      #pp-prompt { background: #1a1a2e; border: 1px solid #6366f1; border-radius: 14px; padding: 16px 20px; display: flex; align-items: center; gap: 12px; box-shadow: 0 8px 32px rgba(0,0,0,0.5); animation: ppSlideIn 0.4s cubic-bezier(.16,1,.3,1); max-width: 320px; }
      @keyframes ppSlideIn { from { transform: translateY(20px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
      #pp-prompt p { color: #e2e8f0; font-size: 13px; line-height: 1.4; margin: 0; flex: 1; }
      #pp-allow { background: #6366f1; color: #fff; border: none; border-radius: 8px; padding: 7px 14px; font-size: 12px; font-weight: 600; cursor: pointer; white-space: nowrap; }
      #pp-allow:hover { background: #818cf8; }
      #pp-dismiss { background: none; border: none; color: #94a3b8; font-size: 18px; cursor: pointer; line-height: 1; padding: 0 4px; }
    `;
        document.head.appendChild(style);

        const widget = document.createElement('div');
        widget.id = 'pp-widget';
        widget.innerHTML = `
      <div id="pp-prompt">
        <span style="font-size:22px">🔔</span>
        <p>Get instant updates — enable notifications.</p>
        <button id="pp-allow">Allow</button>
        <button id="pp-dismiss">×</button>
      </div>
    `;
        document.body.appendChild(widget);

        document.getElementById('pp-allow').addEventListener('click', () => requestPermission(vapidPublicKey, bridgeRequired, useLocalSw));
        document.getElementById('pp-dismiss').addEventListener('click', removeWidget);
    }

    function removeWidget() {
        const w = document.getElementById('pp-widget');
        if (w) w.remove();
    }

    // ─── Public API ──────────────────────────────────────────────────────────────
    window.pushPlatform = {
        async setTag(key, value) {
            const endpoint = getEndpoint();
            if (!endpoint) return;
            await request('POST', '/api/subscriber/tags', { endpoint, tags: { [key]: value } });
        },
        async removeTag(key) {
            const endpoint = getEndpoint();
            if (!endpoint) return;
            await request('DELETE', `/api/subscriber/tags/${key}`, { endpoint });
        },
        async unsubscribe() {
            const endpoint = getEndpoint();
            if (!endpoint) return;
            await request('DELETE', '/api/unsubscribe', { endpoint });
            try { localStorage.removeItem('pp_endpoint'); } catch { }
        }
    };

    function getEndpoint() {
        try { return localStorage.getItem('pp_endpoint'); } catch { return null; }
    }

    // ─── Browser / OS Detection ──────────────────────────────────────────────────
    function detectBrowser(ua) {
        if (/Edg\//.test(ua)) return 'Edge';
        if (/OPR\/|Opera\//.test(ua)) return 'Opera';
        if (/Firefox\//.test(ua)) return 'Firefox';
        if (/Chrome\//.test(ua)) return 'Chrome';
        if (/Safari\//.test(ua)) return 'Safari';
        return 'Unknown';
    }
    function detectOS(ua) {
        if (/Windows/.test(ua)) return 'Windows';
        if (/Android/.test(ua)) return 'Android';
        if (/iPhone|iPad/.test(ua)) return 'iOS';
        if (/Mac/.test(ua)) return 'macOS';
        if (/Linux/.test(ua)) return 'Linux';
        return 'Unknown';
    }

    // ─── Boot ───────────────────────────────────────────────────────────────────
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
